import { test, expect } from '@playwright/test';
import { onlyLocal } from './helpers';
for (const width of [390, 768, 1440]) test(`home offers a fictional area example at ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await onlyLocal(page);
  await page.goto('/');
  const example = page.locator('.product-example');
  await expect(example).toContainText('가상부지 A · 계산 체험 예시');
  await expect(example).toContainText('5,000㎡ 부족');
  await expect(example).toContainText('면적 충족');
  await expect(example.locator('img')).toHaveCount(0);
  await expect(example).not.toContainText(/반곡동|77점|B등급/);
  await expect(example.getByRole('link', { name: /예시로 바로 체험하기/ })).toHaveAttribute('href', '/review?example=area');
  await expect(example.getByRole('link', { name: /두 후보 비교 체험하기/ })).toHaveAttribute('href', '/review?example=compare');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/project#example');
  await expect(page.locator('#example')).toContainText('가상부지 A');
  await expect(page.locator('#example')).toContainText('15,000㎡');
  await expect(page.locator('#example')).not.toContainText(/77점|반곡동/);
});
