import { chromium } from 'playwright';
import { writeFileSync,mkdirSync } from 'node:fs';
import { cpus,platform,release,arch,totalmem } from 'node:os';
const base='http://127.0.0.1:5208';const dir=new URL('./artifacts/',import.meta.url);mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true});const runs=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR'});
 await context.route('**/*',async r=>{if(new URL(r.request().url()).origin!==base)return r.abort();if(r.request().url().includes('/api/'))await new Promise(resolve=>setTimeout(resolve,100));return r.continue();});
 const page=await context.newPage();const apiPaths=[];page.on('request',request=>{const path=new URL(request.url()).pathname;if(path.startsWith('/api/'))apiPaths.push(path);});const start=performance.now();await page.goto(base+'/review');await page.locator('.workspace-toolbar').waitFor();const coldAppReadyMs=performance.now()-start;
 for(let i=0;i<6;i++){
  if(i)await page.getByRole('button',{name:'검토 내용 지우기',exact:true}).click();
  const requestsBefore=apiPaths.length;
  await page.getByRole('combobox',{name:'부지 검색'}).fill('36.4967, 127.3007');
  const pending=page.evaluate(()=>new Promise(resolve=>{const field=document.querySelector('#site-search-input');field.addEventListener('keydown',()=>{const start=performance.now();let first=null;const check=()=>{if(first===null&&document.querySelector('.result-overview'))first=performance.now()-start;const done=document.querySelectorAll('.online-evidence-status>div>span');if(first!==null&&done.length===3&&Array.from(done).every(e=>e.textContent.endsWith('조회 완료')))requestAnimationFrame(()=>resolve({firstResultMs:first,settledMs:performance.now()-start}));else requestAnimationFrame(check);};requestAnimationFrame(check);},{once:true});}));
  await page.getByRole('combobox',{name:'부지 검색'}).press('Enter');const result=await pending;
  await page.getByRole('button',{name:/상세조건 입력/}).click();await page.locator('summary').filter({hasText:'사업비와 차입조건'}).click();await page.getByRole('spinbutton',{name:/지연 중 평균 차입잔액/}).fill('1000');await page.locator('summary').filter({hasText:'금리·지연기간 가정'}).click();
  await page.locator('.panel-action button').first().click();
  const comparePending=page.evaluate(()=>new Promise(resolve=>{const field=Array.from(document.querySelectorAll('input')).find(e=>e.closest('label')?.textContent.startsWith('금리 가정 2'));field.addEventListener('input',()=>{const start=performance.now();const check=()=>{const cell=document.querySelector('dialog[open] .sensitivity-table tbody tr:nth-child(2) td:nth-child(3)');if(cell?.textContent==='70억원')requestAnimationFrame(()=>resolve(performance.now()-start));else requestAnimationFrame(check);};requestAnimationFrame(check);},{once:true});}));
  await page.getByRole('spinbutton',{name:/금리 가정 2/}).fill('7');await page.locator('.header-saved').click();const compareUpdateMs=await comparePending;await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'보고서 · PDF',exact:true}).click();
  const reportPending=page.evaluate(()=>new Promise(resolve=>{document.querySelector('.report-open-button').addEventListener('click',()=>{const start=performance.now();const check=()=>{if(document.querySelector('#print-root [data-snapshot-id]')&&document.querySelector('.report-frozen-preview'))requestAnimationFrame(()=>resolve(performance.now()-start));else requestAnimationFrame(check);};requestAnimationFrame(check);},{once:true});}));
  await page.locator('.report-open-button').click();const reportOpenMs=await reportPending;const paths=apiPaths.slice(requestsBefore);const apiRequestsByPath=Object.fromEntries([...new Set(paths)].map(path=>[path,paths.filter(p=>p===path).length]));runs.push({cache:i===0?'cold application and lookups':'warm in-memory bundle/lookup caches',apiRequestsByPath,onlineLookupRequests:paths.filter(path=>['/api/zoning','/api/restrictions','/api/disaster'].includes(path)).length,...result,compareUpdateMs,reportOpenMs});
 }
 const warm=runs.slice(1);const summary=Object.fromEntries(['firstResultMs','settledMs','compareUpdateMs','reportOpenMs'].map(k=>{const v=warm.map(r=>r[k]).sort((a,b)=>a-b);return[k,{cold:runs[0][k],warmMedian:v[2],warmMax:Math.max(...v)}]}));
 const out={at:new Date().toISOString(),environment:{browser:browser.version(),node:process.version,platform:platform(),release:release(),arch:arch(),cpu:cpus()[0].model,logicalCpu:cpus().length,memoryGiB:totalmem()/2**30,viewport:'1440x1000',build:'production dist',cpuThrottle:'none',network:'loopback static assets, API fixture each100ms delay, external requests blocked; no network throughput throttle',repeat:'one cold context + five same-context reset/reviews; no concurrent QA during intended final measurement'},definitions:{coldAppReadyMs:'Node navigation start until search toolbar mounted, includes first data loading',firstResultMs:'search Enter event until first rendered result animation frame; does not require online completion',settledMs:'search Enter event until all three lookup status labels complete and next animation frame',compareUpdateMs:'common rate input event 5.5→7 until open comparison displays 70억원 and next frame; includes automated subsequent compare button action',reportOpenMs:'report-open click event until frozen preview+print DOM exists and next frame'},coldAppReadyMs,runs,summary,localTargets:{compareMs:250,reportMs:500,notBusinessSavings:true,notDeploymentGuarantee:true}};writeFileSync(new URL('performance.json',dir),JSON.stringify(out,null,2));console.log(JSON.stringify(summary,null,2));
}finally{await browser.close();}
