import { test, expect } from '@playwright/test';
import { pick, numeric, report, navigate, onlyLocal } from './helpers';
for (const width of [390,768,1440]) test(`R12-R24 R32-R34 complete workflow ${width}`, async ({page}, info) => {
  await page.setViewportSize({width,height:width===390?844:1000});await onlyLocal(page);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const requests:string[]=[];page.on('request',r=>requests.push(r.url()));
  await page.goto('/');await page.waitForLoadState('networkidle');
  expect(requests.filter(x=>/\/data\/|\/api\/|ReviewApp/.test(x))).toEqual([]);
  await page.getByRole('link',{name:'부지 검토 시작',exact:false}).first().click();
  await expect(page.locator('.workspace-toolbar')).toBeVisible();
  await page.getByRole('combobox',{name:'부지 검색'}).fill('반곡동');
  await page.getByRole('combobox',{name:'부지 검색'}).press('ArrowDown');
  await expect(page.getByRole('combobox',{name:'부지 검색'})).toHaveAttribute('aria-activedescendant',/site-search-option/);
  await page.getByRole('combobox',{name:'부지 검색'}).press('Enter');await expect(page.locator('.current-selection')).toContainText('반곡동');
  await pick(page,'세종시 합성 검수 도로 123');await expect(page.locator('.current-selection')).toContainText('세종특별자치시 합성 주소');
  await pick(page);await report(page);await expect(page.locator('#print-root')).toContainText('계산 보류');expect(requests.some(x=>x.includes('/api/generate'))).toBe(false);
  await page.locator('.report-close-button').click();await numeric(page);
  await expect(page.locator('.review-decision')).toContainText('5,000㎡ 부족');
  await page.getByRole('button',{name:'평',exact:true}).click();expect(Number(await page.getByRole('spinbutton',{name:/대지면적/}).inputValue())).toBeCloseTo(3025,3);
  await page.getByRole('button',{name:'㎡',exact:true}).click();expect(Number(await page.getByRole('spinbutton',{name:/대지면적/}).inputValue())).toBeCloseTo(10000,3);
  await page.locator('.panel-action button').first().click();await expect(page.locator('.header-saved')).toContainText('1');
  for(let i=1;i<4;i++){await pick(page,`${36.4967+i*.001}, 127.3007`);await page.locator('.panel-action .secondary-action').click();}
  await pick(page,'36.51, 127.3007');await expect(page.locator('.panel-action .secondary-action')).toBeDisabled();
  await page.getByRole('button',{name:'담은 후보 4',exact:true}).click();await expect(page.locator('dialog')).toContainText('아래 비교에 현재 후보는 포함되지 않음');
  expect(await page.locator('.comparison-cards article').count()).toBe(4);
  const focusables=page.locator('dialog button');await focusables.last().focus();await page.keyboard.press('Tab');expect(await page.locator('dialog').evaluate(d=>d.contains(document.activeElement))).toBe(true);
  await page.keyboard.press('Shift+Tab');expect(await page.locator('dialog').evaluate(d=>d.contains(document.activeElement))).toBe(true);
  const remove=width<1024?page.locator('.comparison-cards article').first().getByRole('button',{name:'이 후보 제거',exact:true}):page.locator('dialog').getByRole('button',{name:/제거/}).last();
  await remove.click();await page.keyboard.press('Escape');await expect(page.locator('.header-saved')).toContainText('3');
  await expect(page.locator('.header-saved')).toBeFocused();await page.locator('.panel-action .secondary-action').click();await expect(page.locator('.header-saved')).toContainText('4');
  await navigate(page,'프로젝트 소개');await page.reload();await expect(page.locator('h1')).toBeVisible();await page.goBack();await expect(page.locator('.workspace-toolbar')).toBeVisible();await page.goForward();await expect(page.locator('h1')).toBeVisible();
  await navigate(page,'팀 소개');await page.reload();await expect(page.locator('h1')).toContainText('우리가 계약서를 덮고');await navigate(page,'부지 검토');await page.reload();await expect(page.locator('.header-saved')).toContainText('4');
  await pick(page);await numeric(page);await report(page);
  await expect(page.locator('#print-root')).toContainText('15,000㎡');await expect(page.locator('#print-root')).toContainText('60억원');
  const snap=await page.locator('#print-root [data-snapshot-id]').getAttribute('data-snapshot-id');const snapshotText=await page.locator('#print-root').textContent();
  await pick(page,'36.5067, 127.3007');expect(await page.locator('#print-root').textContent()).toBe(snapshotText);
  await pick(page,'38.8, 127');expect(await page.locator('#print-root [data-snapshot-id]').getAttribute('data-snapshot-id')).toBe(snap);
  await page.getByRole('button',{name:'보고서 · PDF',exact:true}).click();await expect(page.locator('.report-open-button')).toBeDisabled();await expect(page.locator('.report-pdf-button')).toBeEnabled();
  await page.screenshot({path:info.outputPath('complete.png')});expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);
  await navigate(page,'프로젝트 소개');await expect(page.locator('#print-root')).toHaveCount(0);expect(errors).toEqual([]);
});
